package it.polimi.ingsw.model.achievement;

public enum PublicAchievementNames {
    COLORDIAGONALS,COLORVARIETY,COLUMNCOLORVARIETY,COLUMNSHADEVARIETY,ROWCOLORVARIETY,ROWSHADEVARIETY,SHADE12,SHADE34,SHADE56,SHADEVARIETY
}
